"""
Automatic Image Annotation Pipeline
====================================
Uses GroundingDINO (via Autodistill) to generate YOLO-format bounding box
annotations for the Traffic_dataset (BDD100K subset).

Output structure
----------------
Traffic_dataset/
  train/          <- source images (unchanged)
  val/            <- source images (unchanged)
  test/           <- source images (unchanged)
  labels/
    train/        <- YOLO .txt label files for train images
    val/          <- YOLO .txt label files for val images
    test/         <- YOLO .txt label files for test images
  data.yaml       <- ready for ultralytics / YOLOv8 training

Resume support: already-labeled images are skipped automatically.
"""

import glob
import os
import sys
import time

import cv2
import numpy as np
import torch
from tqdm import tqdm

from autodistill.detection import CaptionOntology
from autodistill_grounding_dino import GroundingDINO

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DATASET_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "Traffic_dataset")

# Text prompts → YOLO class names (order determines class id)
ONTOLOGY_MAP = {
    "car": "car",            # class 0
    "bus": "bus",            # class 1
    "traffic light": "traffic_light",  # class 2
    "person": "person", # class 3
    "tree ": "tree", # class 4
    "Buildings": "buildings"  # class 5
}

SPLITS = ["train", "val", "test"]
IMAGE_EXT = ".jpg"

# Detection thresholds – tune these to balance recall vs. false positives
BOX_THRESHOLD  = 0.35
TEXT_THRESHOLD = 0.25

# Apply class-agnostic NMS to suppress duplicate boxes from overlapping prompts
APPLY_NMS    = True
NMS_IOU_THRESH = 0.5

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def write_yolo_label(label_path: str,
                     detections,
                     img_w: int,
                     img_h: int) -> int:
    """Write a YOLO-format .txt file; returns number of annotations written."""
    os.makedirs(os.path.dirname(label_path), exist_ok=True)
    lines = []
    if detections is not None and len(detections) > 0:
        for xyxy, cls_id in zip(detections.xyxy, detections.class_id):
            x1, y1, x2, y2 = xyxy
            cx = ((x1 + x2) / 2) / img_w
            cy = ((y1 + y2) / 2) / img_h
            w  = (x2 - x1) / img_w
            h  = (y2 - y1) / img_h
            # Clamp to [0, 1]
            cx, cy = max(0.0, min(1.0, cx)), max(0.0, min(1.0, cy))
            w,  h  = max(0.0, min(1.0, w)),  max(0.0, min(1.0, h))
            if w > 0 and h > 0:
                lines.append(f"{int(cls_id)} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
    with open(label_path, "w") as f:
        f.write("\n".join(lines))
    return len(lines)


def write_data_yaml(dataset_root: str, classes: list[str]) -> str:
    """Write data.yaml for ultralytics / YOLOv8 training."""
    yaml_path = os.path.join(dataset_root, "data.yaml")
    yaml_content = (
        f"# Auto-generated by auto_annotate.py\n"
        f"path: {dataset_root}\n"
        f"train: train\n"
        f"val: val\n"
        f"test: test\n"
        f"\n"
        f"nc: {len(classes)}\n"
        f"names: {classes}\n"
        f"\n"
        f"# Label files are in Traffic_dataset/labels/{{train,val,test}}/\n"
        f"# To train with ultralytics, symlink or move images into\n"
        f"# Traffic_dataset/images/{{train,val,test}}/ first.\n"
    )
    with open(yaml_path, "w") as f:
        f.write(yaml_content)
    return yaml_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("Automatic Annotation Pipeline  –  GroundingDINO + Autodistill")
    print("=" * 60)
    print(f"Dataset root : {DATASET_ROOT}")
    print(f"Device       : {'CUDA (' + torch.cuda.get_device_name(0) + ')' if torch.cuda.is_available() else 'CPU (slow!)'}")
    print(f"Splits       : {SPLITS}")
    print(f"Classes      : {list(ONTOLOGY_MAP.values())}")
    print(f"Box threshold: {BOX_THRESHOLD}  |  Text threshold: {TEXT_THRESHOLD}")
    print()

    # -----------------------------------------------------------------------
    # 1. Build ontology & load model (downloads weights on first run)
    # -----------------------------------------------------------------------
    ontology = CaptionOntology(ONTOLOGY_MAP)
    classes  = ontology.classes()          # ['car', 'bus', 'traffic_light', 'person']

    print("Loading GroundingDINO model (downloads ~700 MB on first run)...")
    model = GroundingDINO(
        ontology=ontology,
        box_threshold=BOX_THRESHOLD,
        text_threshold=TEXT_THRESHOLD,
    )
    print("Model loaded.\n")

    # -----------------------------------------------------------------------
    # 2. Write data.yaml
    # -----------------------------------------------------------------------
    yaml_path = write_data_yaml(DATASET_ROOT, classes)
    print(f"data.yaml written → {yaml_path}\n")

    # -----------------------------------------------------------------------
    # 3. Annotate each split
    # -----------------------------------------------------------------------
    grand_total_imgs   = 0
    grand_total_labels = 0
    grand_skipped      = 0
    grand_errors       = 0
    t_start = time.time()

    for split in SPLITS:
        img_dir   = os.path.join(DATASET_ROOT, split)
        label_dir = os.path.join(DATASET_ROOT, "labels", split)
        os.makedirs(label_dir, exist_ok=True)

        image_paths = sorted(glob.glob(os.path.join(img_dir, f"*{IMAGE_EXT}")))
        if not image_paths:
            print(f"[{split}] No {IMAGE_EXT} images found in {img_dir} – skipping.")
            continue

        print(f"[{split}] {len(image_paths)} images → labels → {label_dir}")

        split_labels  = 0
        split_skipped = 0
        split_errors  = 0

        pbar = tqdm(image_paths, desc=f"  {split}", unit="img", dynamic_ncols=True)
        for img_path in pbar:
            stem       = os.path.splitext(os.path.basename(img_path))[0]
            label_path = os.path.join(label_dir, stem + ".txt")

            # Resume support – skip if already labeled
            if os.path.exists(label_path):
                split_skipped += 1
                continue

            try:
                image = cv2.imread(img_path)
                if image is None:
                    raise ValueError(f"cv2.imread returned None for {img_path}")
                img_h, img_w = image.shape[:2]

                detections = model.predict(image)

                # Class-agnostic NMS to remove overlapping boxes
                if APPLY_NMS and detections is not None and len(detections) > 0:
                    detections = detections.with_nms(
                        threshold=NMS_IOU_THRESH, class_agnostic=True
                    )

                n = write_yolo_label(label_path, detections, img_w, img_h)
                split_labels += n
                pbar.set_postfix(annotations=split_labels, skipped=split_skipped)

            except Exception as e:
                split_errors += 1
                # Write empty label so we know the image was processed
                with open(label_path, "w") as f:
                    pass
                tqdm.write(f"  [ERROR] {os.path.basename(img_path)}: {e}")

        grand_total_imgs   += len(image_paths)
        grand_total_labels += split_labels
        grand_skipped      += split_skipped
        grand_errors       += split_errors

        print(f"  ✓ {split}: {len(image_paths) - split_skipped - split_errors} processed, "
              f"{split_skipped} skipped, {split_errors} errors, "
              f"{split_labels} annotations written\n")

    # -----------------------------------------------------------------------
    # 4. Summary
    # -----------------------------------------------------------------------
    elapsed = time.time() - t_start
    print("=" * 60)
    print("ANNOTATION COMPLETE")
    print(f"  Total images   : {grand_total_imgs}")
    print(f"  Skipped (done) : {grand_skipped}")
    print(f"  Errors         : {grand_errors}")
    print(f"  Total annotations written : {grand_total_labels}")
    print(f"  Elapsed time   : {elapsed / 60:.1f} min")
    print(f"  data.yaml      : {yaml_path}")
    print("=" * 60)

    # -----------------------------------------------------------------------
    # 5. Quick verification pass
    # -----------------------------------------------------------------------
    print("\nRunning verification...")
    for split in SPLITS:
        label_dir   = os.path.join(DATASET_ROOT, "labels", split)
        img_dir     = os.path.join(DATASET_ROOT, split)
        image_paths = glob.glob(os.path.join(img_dir, f"*{IMAGE_EXT}"))
        label_paths = glob.glob(os.path.join(label_dir, "*.txt"))
        non_empty   = sum(1 for p in label_paths if os.path.getsize(p) > 0)
        print(f"  [{split}] images: {len(image_paths):5d}  "
              f"label files: {len(label_paths):5d}  "
              f"non-empty labels: {non_empty:5d}")
    print("\nDone. Labels are in Traffic_dataset/labels/{train,val,test}/")


if __name__ == "__main__":
    main()
